#!/usr/bin/env node

// Pre-merge hook - creates checkpoint before merge
const path = require('path');
const mainPath = path.join(__dirname, '..', '..');
const { createCheckpoint } = require(path.join(mainPath, 'dist', 'snapshot', 'create'));

createCheckpoint('merge');
